### ISSUE TITLE
Ability to return other types besides boolean

### ISSUE THREAD

**Issue by h4ux** [upstash/edge-flags#27]
This is a very nice solution to manage feature flags by turning on and off or create a simple AB test.
If the result could also be a string or an integer it will expand the usage greatly and allow to serve different variations of a feature.

Example, have 3 signup forms and serve 1 for all the countries while AB test 2 and 3 for US.

**Comment by ytkimirti** [comment]
Sorry for the late reply. I really like the idea, this repo is not developed that much currently but in the future it is possible
